In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
Data=pd.read_csv("https://raw.githubusercontent.com/training-ml/Files/main/breast%20cancer.csv")

In [4]:
Data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
Data.shape

(569, 33)

In [7]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [8]:
Data.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [11]:
Data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [14]:
Data.drop(Data.columns[[0,32]],axis=1,inplace=True)

In [15]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [16]:
Data.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [18]:
Data["diagnosis"]=Data["diagnosis"].replace({"M":1,"B":0})

In [19]:
Data["diagnosis"].unique()

array([1, 0], dtype=int64)

In [20]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    int64  
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [21]:
from sklearn.feature_selection import SelectKBest, f_classif

In [25]:
X=Data.drop("diagnosis",axis=1)
Y=Data["diagnosis"]

In [32]:
bf= SelectKBest(score_func=f_classif,k=20)
fit=bf.fit(X,Y)
scores=pd.DataFrame(fit.scores_)
columns=pd.DataFrame(X.columns)
Total_Scores=pd.concat([columns,scores],axis=1)
Total_Scores.columns=["Feature Name","Scores"]
print(Total_Scores.nlargest(20,"Scores"))

            Feature Name      Scores
27  concave points_worst  964.385393
22       perimeter_worst  897.944219
7    concave points_mean  861.676020
20          radius_worst  860.781707
2         perimeter_mean  697.235272
23            area_worst  661.600206
0            radius_mean  646.981021
3              area_mean  573.060747
6         concavity_mean  533.793126
26       concavity_worst  436.691939
5       compactness_mean  313.233079
25     compactness_worst  304.341063
10             radius_se  268.840327
12          perimeter_se  253.897392
13               area_se  243.651586
21         texture_worst  149.596905
24      smoothness_worst  122.472880
28        symmetry_worst  118.860232
1           texture_mean  118.096059
17     concave points_se  113.262760


In [34]:
Data2=Data[["concave points_worst","perimeter_worst","concave points_mean","radius_worst","perimeter_mean","area_worst","radius_mean","area_mean","concavity_mean","concavity_worst","compactness_mean","compactness_worst","radius_se","perimeter_se","area_se","texture_worst","smoothness_worst","symmetry_worst","texture_mean","concave points_se"]]
Data2

concave points_worst  perimeter_worst  concave points_mean  radius_worst  \
0                  0.2654           184.60              0.14710        25.380   
1                  0.1860           158.80              0.07017        24.990   
2                  0.2430           152.50              0.12790        23.570   
3                  0.2575            98.87              0.10520        14.910   
4                  0.1625           152.20              0.10430        22.540   
..                    ...              ...                  ...           ...   
564                0.2216           166.10              0.13890        25.450   
565                0.1628           155.00              0.09791        23.690   
566                0.1418           126.70              0.05302        18.980   
567                0.2650           184.60              0.15200        25.740   
568                0.0000            59.16              0.00000         9.456   

     perimeter_mean  area_worst  radius_mean  area_mean  concavity_mean  \
0            122.80      2019.0        17.99     1001.0         0.30010   
1            132.90      1956.0        20.57     1326.0         0.08690   
2            130.00      1709.0        19.69     1203.0         0.19740   
3             77.58       567.7        11.42      386.1         0.24140   
4            135.10      1575.0        20.29     1297.0         0.19800   
..              ...         ...          ...        ...             ...   
564          142.00      2027.0        21.56     1479.0         0.24390   
565          131.20      1731.0        20.13     1261.0         0.14400   
566          108.30      1124.0        16.60      858.1         0.09251   
567          140.10      1821.0        20.60     1265.0         0.35140   
568           47.92       268.6         7.76      181.0         0.00000   

     concavity_worst  compactness_mean  compactness_worst  radius_se  \
0             0.7119           0.27760            0.66560     1.0950   
1             0.2416           0.07864            0.18660     0.5435   
2             0.4504           0.15990            0.42450     0.7456   
3             0.6869           0.28390            0.86630     0.4956   
4             0.4000           0.13280            0.20500     0.7572   
..               ...               ...                ...        ...   
564           0.4107           0.11590            0.21130     1.1760   
565           0.3215           0.10340            0.19220     0.7655   
566           0.3403           0.10230            0.30940     0.4564   
567           0.9387           0.27700            0.86810     0.7260   
568           0.0000           0.04362            0.06444     0.3857   

     perimeter_se  area_se  texture_worst  smoothness_worst  symmetry_worst  \
0           8.589   153.40          17.33           0.16220          0.4601   
1           3.398    74.08          23.41           0.12380          0.2750   
2           4.585    94.03          25.53           0.14440          0.3613   
3           3.445    27.23          26.50           0.20980          0.6638   
4           5.438    94.44          16.67           0.13740          0.2364   
..            ...      ...            ...               ...             ...   
564         7.673   158.70          26.40           0.14100          0.2060   
565         5.203    99.04          38.25           0.11660          0.2572   
566         3.425    48.55          34.12           0.11390          0.2218   
567         5.772    86.22          39.42           0.16500          0.4087   
568         2.548    19.15          30.37           0.08996          0.2871   

     texture_mean  concave points_se  
0           10.38            0.01587  
1           17.77            0.01340  
2           21.25            0.02058  
3           20.38            0.01867  
4           14.34            0.01885  
..            ...                ...  
564         22.39            0.02454  
565  

In [35]:
Scalar=StandardScaler()
X_Scaled=Scalar.fit_transform(Data2)

In [36]:
X_Scaled

array([[ 2.29607613,  2.30360062,  2.53247522, ...,  2.75062224,
        -2.07333501,  0.66081994],
       [ 1.0870843 ,  1.53512599,  0.54814416, ..., -0.24388967,
        -0.35363241,  0.26016207],
       [ 1.95500035,  1.34747521,  2.03723076, ...,  1.152255  ,
         0.45618695,  1.42482747],
       ...,
       [ 0.41406869,  0.57900058,  0.10577736, ..., -1.10454895,
         2.0455738 ,  0.61215704],
       [ 2.28998549,  2.30360062,  2.65886573, ...,  1.91908301,
         2.33645719,  0.78572138],
       [-1.74506282, -1.43273495, -1.26181958, ..., -0.04813821,
         1.22179204, -1.91344745]])

In [38]:
X_Scaled.shape[1]

20

In [41]:
vif=pd.DataFrame()
vif["vif"]=[variance_inflation_factor(X_Scaled,i) for i in range(X_Scaled.shape[1])]
vif["Features"]=Data2.columns
vif

vif              Features
0     29.382639  concave points_worst
1    375.222798       perimeter_worst
2     43.647672   concave points_mean
3    701.458806          radius_worst
4   3396.693780        perimeter_mean
5    298.937711            area_worst
6   3472.800451           radius_mean
7    308.388102             area_mean
8     48.716793        concavity_mean
9     26.829230       concavity_worst
10    30.009606      compactness_mean
11    16.974869     compactness_worst
12    65.096231             radius_se
13    60.575878          perimeter_se
14    34.759183               area_se
15     9.307059         texture_worst
16     2.895779      smoothness_worst
17     1.942653        symmetry_worst
18     8.540855          texture_mean
19     5.209730     concave points_se

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X_Scaled,Y,test_size=0.25)

In [44]:
log_reg=LogisticRegression()

In [45]:
log_reg.fit(X_train,y_train)

LogisticRegression()

In [46]:
pred_y=log_reg.predict(X_test)

In [59]:
pred_y

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [60]:
accuracy=accuracy_score(y_test,pred_y)

In [61]:
accuracy

0.986013986013986

In [62]:
confusion_matrix= confusion_matrix(y_test,pred_y)

TypeError: 'numpy.ndarray' object is not callable

In [51]:
confusion_matrix

array([[91,  1],
       [ 1, 50]], dtype=int64)

In [52]:
CR= classification_report(y_test,pred_y)
CR

'              precision    recall  f1-score   support\n\n           0       0.99      0.99      0.99        92\n           1       0.98      0.98      0.98        51\n\n    accuracy                           0.99       143\n   macro avg       0.98      0.98      0.98       143\nweighted avg       0.99      0.99      0.99       143\n'

In [53]:
Knn= KNeighborsClassifier()
Knn.fit(X_train,y_train)

KNeighborsClassifier()

In [54]:
Y_Pred=Knn.predict(X_test)
Y_Pred

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [55]:
accuracy=accuracy_score(y_test,Y_Pred)
accuracy

0.958041958041958

In [56]:
confusion_matrix= confusion_matrix(y_test,Y_Pred)
confusion_matrix

TypeError: 'numpy.ndarray' object is not callable